# Meta Data for SEO

## Homepage
title = "Apuntes de Francisco Sanhueza Matamala"
titleSeparator = "-"
logo = "images/panchito_transparent.png"
logoDark = "images/panchito_transparent.png"
titleAddition = "Cosas que me importan"
description = "Francisco Sanhueza Matamala"

## Open Graph + Twitter Cards
images = ["logo_redondo.png"]
twitterSite = "dccuchile"
twitterCreator = "dccuchile"
ogLocale = "es_CL"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/dccuchile"
schemaLinkedIn = "https://www.linkedin.com/in/dccuchile/"
schemaGitHub = "https://github.com/cc5325"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Sitio generado con <a href=\"https://gohugo.io/\">Hugo</a> y <a href=\"https://getdoks.org/\">Doks</a>"
footer2 = "<a href=\"https://francisco.sanhueza.net/\">Página web principal</a>"

# Alert
alert = false
alertText = "CTFs: jueves de 18:00 a 21:00 hrs | Auxiliares: Lunes de 18:15 a 20:00 hrs"

# Edit Page
docsRepo = "https://github.com/Pan-con-queso/apuntes"
editPage = true
